name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Get more space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30720
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: armbian/build
        ref: main
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
          echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/board-dts-add-h88k.patch -O patch/kernel/rockchip-rk3588-legacy/board-makefile-add-h88k.patch
        mkdir -p arch/arm64/boot/dts/rockchip/
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/rk3588-h88k.dts -O arch/arm64/boot/dts/rockchip/rk3588-h88k.dts
        git diff --no-index --output=./patch/kernel/rockchip-rk3588-legacy/board-dts-add-h88k.patch /dev/null arch/arm64/boot/dts/rockchip/rk3588-h88k.dts || ls -l ./patch/kernel/rockchip-rk3588-legacy/board-dts-add-h88k.patch
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/h88k.csc -O config/boards/h88k.csc
        cp -r patch/u-boot/legacy/board_rock-5b patch/u-boot/legacy/board_h88k
        wget https://raw.githubusercontent.com/amazingfate/build/rk3588-new-legacy/config/kernel/linux-rockchip-rk3588-legacy.config -O config/kernel/linux-rockchip-rk3588-legacy.config
        rm patch/kernel/rockchip-rk3588-legacy/20*.patch patch/kernel/rockchip-rk3588-legacy/999*.patch
        sed -i "s|radxa/kernel|armbian/linux-rockchip|g" config/sources/families/rockchip-rk3588.conf
        sed -i "s|linux-5.10-gen-rkr3.4|rockchip-5.10|g" config/sources/families/rockchip-rk3588.conf
        sed -i "s|ext4|fat|g" config/boards/rock-5b.wip
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/backport-v6.0.16.patch -O patch/kernel/archive/rk35xx-5.10/backport-6.0.16.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/board-add-hinlink-h6xk-makefile.patch -O patch/kernel/archive/rk35xx-5.10/board-add-hinlink-h6xk-makefile.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/rk3568-hinlink-h6xk.dtsi -O arch/arm64/boot/dts/rockchip/rk3568-hinlink-h6xk.dtsi
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/rk3568-hinlink-h66k.dts -O arch/arm64/boot/dts/rockchip/rk3568-hinlink-h66k.dts
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/rk3568-hinlink-h68k.dts -O arch/arm64/boot/dts/rockchip/rk3568-hinlink-h68k.dts
        git diff --no-index --output=./patch/kernel/archive/rk35xx-5.10/rk3568-dtsi-add-hinlink-h6xk.patch /dev/null arch/arm64/boot/dts/rockchip/rk3568-hinlink-h6xk.dtsi || ls -l ./patch/kernel/archive/rk35xx-5.10/rk3568-dtsi-add-hinlink-h6xk.patch
        git diff --no-index --output=./patch/kernel/archive/rk35xx-5.10/board-dts-add-hinlink-h66k.patch /dev/null arch/arm64/boot/dts/rockchip/rk3568-hinlink-h66k.dts || ls -l ./patch/kernel/archive/rk35xx-5.10/board-dts-add-hinlink-h66k.patch
        git diff --no-index --output=./patch/kernel/archive/rk35xx-5.10/board-dts-add-hinlink-h68k.patch /dev/null arch/arm64/boot/dts/rockchip/rk3568-hinlink-h68k.dts || ls -l ./patch/kernel/archive/rk35xx-5.10/board-dts-add-hinlink-h68k.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/linux-rk35xx-legacy.config -O config/kernel/linux-rk35xx-legacy.config
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/hinlink-h66k.conf -O config/boards/hinlink-h66k.conf
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/hinlink-h68k.conf -O config/boards/hinlink-h68k.conf
        git status
        docker pull ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
        ./compile.sh \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        DESKTOP_ENVIRONMENT=${{ env.desktop-environment }} \
        DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ env.desktop-environment-config-name }} \
        DESKTOP_APPGROUPS_SELECTED=${{ env.desktop_appgroups_selected }} \
        EXPERT=${{ env.expert }} \
        BOARD_FIRMWARE_INSTALL="-full" \
        SHARE_LOG=yes \
        DEBUG=yes \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: "./build/output/images/*;./build/output/debs/linux-*.deb"
        draft: false
        overwrite: true
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
