name: 'Armbian/build'
description: 'Armbian Linux build framework'
inputs:
  board:
    required: true
  flavor:
    required: true
  release-id:
    required: false
  github-token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Get more space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 30720
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: amazingfate/build
        ref: add-panfork-mesa
        path: build
    - name: Set env
      shell: bash
      run: |
        if [ ${{ inputs.flavor }} == "debian" ]
        then
          echo "release=sid" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=no" >> $GITHUB_ENV
        elif [ ${{ inputs.flavor }} == "ubuntu" ]
        then
          echo "release=jammy" >> $GITHUB_ENV
          echo "build-minimal=no" >> $GITHUB_ENV
          echo "build-desktop=yes" >> $GITHUB_ENV
          echo "desktop-environment=gnome" >> $GITHUB_ENV
          echo "desktop-environment-config-name=config_base" >> $GITHUB_ENV
          echo "expert=yes" >> $GITHUB_ENV
          if [ ${{ inputs.board }} == "rock-5b" ] || [ ${{ inputs.board }} == "h88k" ]
          then
            if [ ${{ inputs.branch }} == "legacy" ]
            then
              echo "desktop_appgroups_selected=\"browsers chat desktop_tools editors email internet multimedia office panfork-mesa programming remote_desktop\"" >> $GITHUB_ENV
            else
              echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
            fi
          else
            echo "desktop_appgroups_selected=\"3dsupport browsers chat desktop_tools editors email internet multimedia office programming remote_desktop\"" >> $GITHUB_ENV
          fi
        fi
    - name: Build
      shell: bash
      run: |
        cd ./build
        touch .ignore_changes
        sed -i -e 's/-it//g' ./config/templates/config-docker.conf
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/board-dts-add-h88k.patch -O patch/kernel/rockchip-rk3588-legacy/board-makefile-add-h88k.patch
        mkdir -p arch/arm64/boot/dts/rockchip/
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/rk3588-h88k.dts -O arch/arm64/boot/dts/rockchip/rk3588-h88k.dts
        git diff --no-index --output=./patch/kernel/rockchip-rk3588-legacy/board-dts-add-h88k.patch /dev/null arch/arm64/boot/dts/rockchip/rk3588-h88k.dts || ls -l ./patch/kernel/rockchip-rk3588-legacy/board-dts-add-h88k.patch
        wget https://github.com/amazingfate/armbian-h88k-images/raw/master/h88k.csc -O config/boards/h88k.csc
        cp -r patch/u-boot/legacy/board_rock-5b patch/u-boot/legacy/board_h88k
        sed -i "s|# CONFIG_SENSORS_PWM_FAN is not set|CONFIG_SENSORS_PWM_FAN=y|g" config/kernel/linux-rockchip-rk3588-legacy.config
        sed -i "s|ext4|fat|g" config/boards/rock-5b.wip
        sed -i "s|KERNELSOURCE='https://github.com/radxa/kernel'|KERNELSOURCE='https://github.com/friendlyarm/kernel-rockchip'|g" config/sources/families/rk35xx.conf
        sed -i "s|KERNELBRANCH='branch:stable-4.19-rock3'|KERNELBRANCH='branch:nanopi5-v5.10.y_opt'|g" config/sources/families/rk35xx.conf
        cd patch/kernel/ && rm rk35xx-legacy && mkdir -p archive/rk35xx-5.10 && ln -s archive/rk35xx-5.10 rk35xx-legacy && cd ../../
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/backport-5.15.patch -O patch/kernel/archive/rk35xx-5.10/backport-5.15.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/board-add-h86k-makefile.patch -O patch/kernel/archive/rk35xx-5.10/board-add-h86k-makefile.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/rk3568-h68k.dts -O arch/arm64/boot/dts/rockchip/rk3568-h68k.dts
        git diff --no-index --output=./patch/kernel/archive/rk35xx-5.10/board-dts-add-h68k.patch /dev/null arch/arm64/boot/dts/rockchip/rk3568-h68k.dts || ls -l ./patch/kernel/archive/rk35xx-5.10/board-dts-add-h68k.patch
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/linux-rk35xx-legacy.config -O config/kernel/linux-rk35xx-legacy.config
        wget https://github.com/amazingfate/armbian-h68k-images/raw/master/h68k.conf -O config/boards/h68k.conf
        git status
        docker_tag=$(cat VERSION|cut -d "-" -f1) && docker_tag_in_repo=${docker_tag:0:5} && docker pull ghcr.io/armbian/build:${docker_tag_in_repo}-amd64 && docker image tag ghcr.io/armbian/build:${docker_tag_in_repo}-amd64 armbian:$(cat VERSION)
        ./compile.sh docker \
        BOARD=${{ inputs.board }} \
        BRANCH=${{ inputs.branch }} \
        RELEASE=${{ env.release }} \
        BUILD_MINIMAL=${{ env.build-minimal }} \
        BUILD_DESKTOP=${{ env.build-desktop }} \
        KERNEL_ONLY=no \
        KERNEL_CONFIGURE=no \
        DESKTOP_ENVIRONMENT=${{ env.desktop-environment }} \
        DESKTOP_ENVIRONMENT_CONFIG_NAME=${{ env.desktop-environment-config-name }} \
        DESKTOP_APPGROUPS_SELECTED=${{ env.desktop_appgroups_selected }} \
        EXPERT=${{ env.expert }} \
        BOARD_FIRMWARE_INSTALL="-full" \
        COMPRESS_OUTPUTIMAGE=sha,gpg,xz
    - name: Upload
      if: inputs.release-id != '' && inputs.github-token != ''
      uses: xresloader/upload-to-github-release@v1
      env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
        file: ./build/output/images/*
        draft: false
    - name: Rollback release
      if: failure() && inputs.release-id != '' && inputs.github-token != ''
      uses: author/action-rollback@stable
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        release_id: ${{ inputs.release-id }}
